### ISSUE TITLE
How can JS files get access to xblock fields?

### ISSUE THREAD

**Issue by andy-armstrong** [edx/XBlock#150]
I have some settings in my xblock:

```
<myxblock question="Question 1"/>
<myxblock question="Question 2"/>
```

In my HTML, I can do:

```
<p>{self.question}</p>
```

I'm looking for an equivalent syntax for my Javascript. Ned suggested that I submit a ticket as he's not aware of a way to do this. I naively tried:

```
 var question = '{self.question}';
```

but that doesn't work.

**Comment by ewall** [comment]
@andy-armstrong Can you explain more how to passed the field data into the element that the JavaScript receives? I'm stumped...
