### ISSUE TITLE
What happened to the Set field?

### ISSUE THREAD

**Issue by tusbar** [edx/XBlock#309]
Hey,

A while back I added support for `Set` type fields. The PR was merged, but it seems to have been removed altogether as the commits are not even here anymore.

Here’s the PR: https://github.com/edx/XBlock/pull/212

Was something wrong with it so it had to be removed?

I had a XBlock that was depending on it.

cc @dmitchell @cpennington @sarina

**Comment by sarina** [comment]
I'm so confused. I don't see the merged commits in the repo history either: https://github.com/edx/XBlock/commits/master?page=4

**Comment by tusbar** [comment]
@sarina it looks like the repo has been force-pushed and the commit (possibly others?) was left out.

**Comment by sarina** [comment]
oh what?? that's not good - who knows what other commits may have been missed :disappointed: 

Can you make a new pull request with your changes? I'm sure we can get them merged promptly.

**Comment by sarina** [comment]
@tusbar  i don't suppose there are forensics to see a force push?  It'd be nice if github noted it in the history

**Comment by tusbar** [comment]
@sarina  The objects are here, just not included in master: https://github.com/edx/XBlock/commit/8124106ffeced4d12f303e6eac9d8dfa34d27dd4

I’ll do another PR.

**Comment by sarina** [comment]
Cool. We're doing some git magic over here to try to figure out if other commits are missing as well. ugh.

**Comment by sarina** [comment]
@tusbar FYI I've made the PR ^^ we couldn't find anything else that is missing, and unfortunately we can't figure out who force pushed. However we've disabled force pushing on master for all edx/ repos going forward.

**Comment by tusbar** [comment]
@sarina haha, I’ve done it too.

**Comment by tusbar** [comment]
Tests will pass on mine though. :wink:

**Comment by tusbar** [comment]
@sarina how did you disable force pushing? I’ve been looking for that setting on GitHub for years.

**Comment by sarina** [comment]
@tusbar our ops team got in touch with Github directly.

We reached out to github, and they've helpfully put a server side pre-receive hook that blocks force pushes to the default branch (typically 'master') of all of our repos.  Attempting to do a git push --force against master will now result in the following error message:

`! [remote rejected] HEAD -> master (pre-receive hook declined)`

**Comment by tusbar** [comment]
@sarina cool, I’ll try and do that as well. :)

**Comment by smarnach** [comment]
In cases like this one it is worthwhile to check the [Github event log](https://api.github.com/repos/edx/xblock/events?page=10) to figure out what has happened (and what commits got lost).  Currently the log goes back to May 13 and doesn't contain any force pushes to master, so it doesn't help – just pointing it out because it may come in handy in the future.

**Comment by sarina** [comment]
Thanks Sven -  I didn't know about that.
