### ISSUE TITLE
Set up Xblock SDK Error

### ISSUE THREAD

**Issue by wildboardm92** [edx/XBlock#324]
I use Open edX XBlock Tutorial to setup Xblock. I install the XBlock SDK requirements:
`(venv) $ pip install -r requirements.txt`
And I get error:
`Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Storing debug log for failure in /root/.pip/pip.log`
pig.log:
`Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1546, in parse_requirements
    session=session,
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 278, in get_file_content
    raise InstallationError('Could not open requirements file: %s' % str(e))
InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by tusbar** [comment]
You’re running `pip install -r requirements.txt` from the wrong directory…

**Comment by wildboardm92** [comment]
I have found `requirements.txt` in /doc, but I have another question. To create the skeleton files for the XBlock I have to do this: 
```
    (venv) $ xblock-sdk/script/startnew.py
```
But there is no such file in xblock_sdk directory. more than there is no /script directory

**Comment by nedbat** [comment]
@wildboardm92 if you ask your questions on the support mailing list, we can help there: https://groups.google.com/forum/#!forum/edx-code
