### ISSUE TITLE
Django 2 support

### ISSUE THREAD

**Issue by jayvdb** [edx/XBlock#425]
There are likely a few blockers in the dependencies.  One is `django-pyfs`

- [ ] https://github.com/edx/django-pyfs (doesnt have issues enabled, probably as it is a fork)

**Comment by stvstnfrd** [comment]
Django 2.2 support was added here: https://github.com/edx/XBlock/pull/452

Thanks @jayvdb !

**Comment by jayvdb** [comment]
Awesome, it looks like django-pyfs also supports django 2.2
