### ISSUE TITLE
A report for building & testing on linux with python3.8

### ISSUE THREAD

**Issue by drhodes** [edx/XBlock#463]
((The only reason why this summary is using python3.8 is because that was the version of python I happened to be using when I got tox to run! I tried five different builds before getting ./configure correct, anyone reading this should probably stick to the python3.5, as noted in the readme))

This was my first foray into XBlock.  On debian, python3.5/stable appears to be considered so old that all that remains in the repo is `python3.5-minimal/now`, which doesn't sound promising.  So anyways I hit a couple hurdles and thought I would share what I did to get tests running.

Grabbed a copy of python 3.8.3 from the python website.  
```bash
$ sudo apt install libsqlite3-dev
$ mkdir python-3.8.3
```
Then configured python.
```
$ ./configure --enable-loadable-sqlite-extensions --enable-optimizations --prefix=/full/path/to/python-3.8.3
$ make && make install
```
set up the virtualenv
```
$ cd your-virtual-envs
$ virtualenv -p /path/to/python-3.8.3/bin/python3.8 xblock-env-38
```
grabbed xblock
```
$ git clone "https://github.com/edx/XBlock.git"
$ cd XBlock
$ source /path/to/your-virtual-envs/xblock-env-38/bin/activate
$ make requirements
```
Ran into [this issue](https://github.com/pypa/pip/issues/8188) with the new version of pip so had to downgrade 
```
$ pip install --upgrade pip==20.0.2
$ tox 
```
with only 1 test failing
```
===================================== short test summary info =====================================
FAILED xblock/test/django/test_field_translation.py::TestXBlockStringFieldDefaultTranslation::test_lazy_translation
========================== 1 failed, 1367 passed, 371 warnings in 5.88s ===========================
```

Not sure if this is the right place for this note, but maybe it will help someone get started or be of interest to xblock devs.

**Comment by stvstnfrd** [comment]
@drhodes This should have been fixed with https://github.com/edx/XBlock/pull/465 .
Thanks!
